vpc_name           = "dev-vpc"
vpc_cidr_block     = "10.0.0.0/16"
public_subnets     = ["10.0.1.0/24", "10.0.2.0/24"]
availability_zone  = ["us-east-1a", "us-east-1b"]
api_ec2_sg         = "dev-api-sg"
env                = "DEV"
s3_name            = "dev-artifact-java-tomcat00"
region             = "us-east-1"
db_name            = "devdb"
db_username        = "devadmin"
db_instance_class  = "db.t4g.micro"
application_name   = "my-dev-app"
environment_name   = "my-dev-env"
rds_port           = 3306
cluster_name     = "dev-ecs-cluster"
container_image  = "namtn6/mock-springboot-api"
container_port   = 8080
desired_count    = 1
username="admin"
